package com.company.PharmacyDept.UI;

import com.company.PharmacyDept.PharmacyAgent;

import javax.swing.*;
import java.awt.*;

public class AddMedsForm {
    private PharmacyAgent agent;

    private JPanel panel;
    private JTextField medicine;
    private JTextField qty;
    private JButton backButton;
    private JButton confirmAddingButton;

    public AddMedsForm(PharmacyAgent agent) {
        this.agent = agent;

        backButton.addActionListener(e -> {
            System.out.println("Going back ...");
            agent.switchToChoiceForm();
            clearInputs();
        });
        confirmAddingButton.addActionListener(e -> {
            System.out.println("Going back ...");
            // TODO: first check the situation
            agent.addMedsBehavior(medicine.getText(), Integer.parseInt(qty.getText()));
            clearInputs();
        });
    }

    private void clearInputs() {
        medicine.setText("");
        qty.setText("");
    }

    public JPanel getPanel() {
        return panel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("Medecine Name");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel.add(label1, gbc);
        medicine = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel.add(medicine, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Quantity");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel.add(label2, gbc);
        qty = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel.add(qty, gbc);
        backButton = new JButton();
        backButton.setText("Back");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel.add(backButton, gbc);
        confirmAddingButton = new JButton();
        confirmAddingButton.setText("Confirm Adding");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel.add(confirmAddingButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
