package com.company.PharmacyDept.UI;

import com.company.PharmacyDept.PharmacyAgent;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.awt.*;

public class ChoiceForm {
    private PharmacyAgent agent;

    private JPanel top;
    private JButton giveMedecineButton;
    private JButton addMedsToStockButton;
    private JPanel panel;
    private JTable inventory;

    public ChoiceForm(PharmacyAgent agent) {
        this.agent = agent;


        giveMedecineButton.addActionListener(e -> {
            System.out.println("Switch to giving mode;");
            agent.switchToGiveMedsForm();
        });

        addMedsToStockButton.addActionListener(e -> {
            System.out.println("Switch to receiving meds;");
            agent.switchToAddMedsForm();
        });
    }

    public JPanel getPanel(String[][] inv) {

        TableModel tableModel = new DefaultTableModel(inv, new String[]{"Medicine", "Quantity"});
        inventory.setModel(tableModel);
        return top;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        top = new JPanel();
        top.setLayout(new GridBagLayout());
        panel = new JPanel();
        panel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.NORTH;
        top.add(panel, gbc);
        giveMedecineButton = new JButton();
        giveMedecineButton.setText("Give Medecine");
        panel.add(giveMedecineButton);
        addMedsToStockButton = new JButton();
        addMedsToStockButton.setText("Add Meds to Stock");
        panel.add(addMedsToStockButton);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        top.add(panel1, gbc);
        final JScrollPane scrollPane1 = new JScrollPane();
        panel1.add(scrollPane1);
        inventory = new JTable();
        scrollPane1.setViewportView(inventory);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return top;
    }

}
