package com.company.WardDept.UI;

import com.company.WardDept.WardAgent;

import javax.swing.*;
import java.awt.*;

public class CheckoutForm {
    private WardAgent agent;

    private JPanel panel;
    private JButton backButton;
    private JButton checkOutButton;
    private JTextField bed;
    private JTextField patientId;

    public CheckoutForm(WardAgent agent) {
        this.agent = agent;

        checkOutButton.addActionListener(e -> {
            System.out.println("checking xxx out :  " + patientId);
            agent.checkoutPatient(patientId.getText(), Integer.parseInt(bed.getText()));
            clearInputs();
        });
        backButton.addActionListener(e -> {
            System.out.println("Going back");
            clearInputs();
            agent.switchToChoiceForm();

        });
    }

    public JPanel getPanel() {
        return panel;
    }

    private void clearInputs() {
        patientId.setText("");
        bed.setText("");
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("Patient Id");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Bed Number");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel.add(label2, gbc);
        backButton = new JButton();
        backButton.setText("Back");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel.add(backButton, gbc);
        checkOutButton = new JButton();
        checkOutButton.setText("Check Out");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        panel.add(checkOutButton, gbc);
        bed = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel.add(bed, gbc);
        patientId = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel.add(patientId, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
