package com.company.EmergencyDept.UI;

import com.company.EmergencyDept.EmergencyAgent;

import javax.swing.*;
import java.awt.*;

public class ChoiceForm {
    private EmergencyAgent agent;

    private JPanel panel;
    private JButton registerPatientButton;
    private JButton performTestsButton;
    private JButton scheduleSurgeryButton;

    public ChoiceForm(EmergencyAgent agent) {
        this.agent = agent;

        // Click listeners
        registerPatientButton.addActionListener(e -> {
            System.out.println("Switching to Registration form...");
            agent.switchToRegistrationForm();
        });
        performTestsButton.addActionListener(e -> {
            System.out.println("Switching to Testing form...");
            agent.switchToTestForm();
        });
        scheduleSurgeryButton.addActionListener(e -> {
            System.out.println("Switching to Surgery form...");
            agent.switchToSurgeryForm();
        });
    }

    public JPanel getPanel() {
        return panel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel.setAutoscrolls(false);
        registerPatientButton = new JButton();
        registerPatientButton.setText("Register Patient");
        panel.add(registerPatientButton);
        performTestsButton = new JButton();
        performTestsButton.setText("Perform Tests");
        panel.add(performTestsButton);
        scheduleSurgeryButton = new JButton();
        scheduleSurgeryButton.setText("Schedule Surgery");
        panel.add(scheduleSurgeryButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
