package agents.UI;

import agents.LaboratoryAgent;

import javax.swing.*;
import java.awt.*;

public class NextPatientForm {
    private LaboratoryAgent agent;

    private JPanel panel;
    private JLabel patientId;
    private JButton backButton;


    public NextPatientForm(LaboratoryAgent agent) {
        this.agent = agent;

        backButton.addActionListener(e -> {
            System.out.println("Going back to Choice form...");
            agent.switchToChoiceForm();
        });
    }

    public JPanel getPanel(String patient) {
        patientId.setText(patient == null ? "No Patient" : patient);
        return panel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridBagLayout());
        patientId = new JLabel();
        patientId.setHorizontalAlignment(0);
        patientId.setHorizontalTextPosition(0);
        patientId.setText("Label");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weighty = 1.0;
        panel.add(patientId, gbc);
        backButton = new JButton();
        backButton.setHorizontalTextPosition(4);
        backButton.setText("Back");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        panel.add(backButton, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Next Patient is: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel.add(label1, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
