package com.company.EmergencyDept.UI;

import com.company.EmergencyDept.EmergencyAgent;
import com.company.LaboratoryDept.LaboratoryAgent;

import javax.swing.*;
import java.awt.*;
import java.util.Arrays;
import java.util.List;

public class TestForm {
    private EmergencyAgent agent;

    private JPanel panel;
    private JTextField patientId;
    private JComboBox<String> comboBox1;
    private JButton backButton;
    private JButton informLabButton;

    private final List<LaboratoryAgent.Specialty> tests = Arrays.asList(LaboratoryAgent.Specialty.values());

    public TestForm(EmergencyAgent agent) {
        this.agent = agent;
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (LaboratoryAgent.Specialty s : tests)
            model.addElement(String.valueOf(s));
        comboBox1.setModel(model);


        backButton.addActionListener(e -> {
            System.out.println("switch to choice ui ...");
            agent.switchToChoiceForm();
        });
        informLabButton.addActionListener(e -> {
            System.out.println("request to lab completed + switch to choice ui ..." + patientId.getText());
            // TODO: inform lab and get their answer back;
            agent.testPatientBehavior(patientId.getText(), LaboratoryAgent.Specialty.valueOf((String) comboBox1.getSelectedItem()));
//            agent.switchToChoiceForm();
        });
    }

    public JPanel getPanel() {
        return panel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("Patient Id");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel.add(label1, gbc);
        patientId = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel.add(patientId, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Test Type");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel.add(label2, gbc);
        comboBox1 = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel.add(comboBox1, gbc);
        backButton = new JButton();
        backButton.setText("Back");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        panel.add(backButton, gbc);
        informLabButton = new JButton();
        informLabButton.setText("Inform Lab");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        panel.add(informLabButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
