package com.company.LaboratoryDept.UI;

import com.company.LaboratoryDept.LaboratoryAgent;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.awt.*;

public class ChoiceForm {
    private LaboratoryAgent agent;

    private JPanel panel;
    private JButton nextPatientButton;
    private JButton enterResultsButton;
    private JTable patients;

    public ChoiceForm(LaboratoryAgent agent) {
        this.agent = agent;

        nextPatientButton.addActionListener(e -> {
            // todo
            System.out.println("Calling next Patient!");
            agent.switchToNextPatientForm();
        });
        enterResultsButton.addActionListener(e -> {
            // todo
            System.out.println("Entering Results");
            agent.switchToEnterResultsForm();
        });
    }

    public JPanel getPanel(String[][] patientss) {
        TableModel tableModel = new DefaultTableModel(patientss, new String[]{"Rank", "PatientId"});
        patients.setModel(tableModel);
        return panel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridBagLayout());
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel.add(panel1, gbc);
        nextPatientButton = new JButton();
        nextPatientButton.setText("Next Patient");
        panel1.add(nextPatientButton);
        enterResultsButton = new JButton();
        enterResultsButton.setText("Enter Results");
        panel1.add(enterResultsButton);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel.add(panel2, gbc);
        final JScrollPane scrollPane1 = new JScrollPane();
        panel2.add(scrollPane1);
        patients = new JTable();
        scrollPane1.setViewportView(patients);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
